### ISSUE TITLE
Error in log, likely a bug in our Netty code

### ISSUE THREAD

**Issue by robotdan** [prime-framework/prime-mvc#10]
```
2022-03-09 11:14:14.830 AM ERROR org.primeframework.mvc.netty.PrimeHTTPServerHandler - Prime encountered an exception while processing the request. This is likely an internal error.
java.lang.NullPointerException: Cannot invoke "java.io.ByteArrayOutputStream.toByteArray()" because "this.outputStream" is null
	at org.primeframework.mvc.netty.PrimeHTTPServerHandler.channelRead0(PrimeHTTPServerHandler.java:132)
	at org.primeframework.mvc.netty.PrimeHTTPServerHandler.channelRead0(PrimeHTTPServerHandler.java:70)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
```

**Comment by robotdan** [comment]
Netty is toast.
