### ISSUE TITLE
Bug in Flash Cookie Scope UnsupportedOperationException

### ISSUE THREAD

**Issue by robotdan** [prime-framework/prime-mvc#7]
```
2022-03-08 06:55:01.794 AM ERROR org.primeframework.mvc.PrimeMVCRequestHandler - Error encountered
java.lang.UnsupportedOperationException: null
        at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
        at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.clear(ImmutableCollections.java:149)
        at org.primeframework.mvc.util.FlashMessageCookie.delete(FlashMessageCookie.java:62)
        at org.primeframework.mvc.message.scope.CookieFlashScope.clear(CookieFlashScope.java:63)
....
2022-03-08 06:55:04.886 AM ERROR org.primeframework.mvc.workflow.DefaultExceptionHandler - Unhandled exception occurred
java.lang.UnsupportedOperationException: null
        at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
        at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.clear(ImmutableCollections.java:149)
        at org.primeframework.mvc.util.FlashMessageCookie.delete(FlashMessageCookie.java:62)
        at org.primeframework.mvc.message.scope.CookieFlashScope.clear(CookieFlashScope.java:63)
        at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:48)
        at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
        at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:45)
```

**Comment by robotdan** [comment]
Fixed, pushed.
