### ISSUE TITLE
Lots of noise with unknown HTTP method such as `HTTPMethod.AZQLNL`.

### ISSUE THREAD

**Issue by robotdan** [prime-framework/prime-mvc#8]
Lots of noise with unknown HTTP method such as `HTTPMethod.AZQLNL`.

Not sure if this problem still exists in `master` now that we are on Netty, but we should test it and make sure we aren't spamming the logs. 

```
2022-03-08 11:02:08.845 PM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInCustomProvider]: IllegalArgumentException: No enum constant HTTPMethod.AZQLNL
  at ServletModule.method(ServletModule.java:57)
      \_ installed by: FusionAuthModule -> Modules$OverrideModule -> MVCModule -> ServletModule
  at FrontEndSupport.<init>(FrontEndSupport.java:145)
      \_ for 10th parameter
  at IndexAction.<init>(IndexAction.java:25)
      \_ for 1st parameter
  while locating IndexAction

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER

1 error

======================
Full classname legend:
======================
FrontEndSupport:          "io.fusionauth.app.service.FrontEndSupport"
FusionAuthModule:         "io.fusionauth.app.guice.FusionAuthModule"
HTTPMethod:               "org.primeframework.mvc.servlet.HTTPMethod"
IndexAction:              "io.fusionauth.app.action.IndexAction"
MVCModule:                "org.primeframework.mvc.guice.MVCModule"
Modules$OverrideModule:   "com.google.inject.util.Modules$OverrideModule"
ServletModule:            "org.primeframework.mvc.servlet.guice.ServletModule"
========================
End of classname legend:
========================

	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138)
	at org.primeframework.mvc.action.DefaultActionMapper.map(DefaultActionMapper.java:61)
	at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:92)
....

Caused by: java.lang.IllegalArgumentException: No enum constant org.primeframework.mvc.servlet.HTTPMethod.AZQLNL
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.primeframework.mvc.servlet.HTTPMethod.valueOf(HTTPMethod.java:23)
	at org.primeframework.mvc.servlet.guice.ServletModule.method(ServletModule.java:57)
	at org.primeframework.mvc.servlet.guice.ServletModule$$FastClassByGuice$$9932012.GUICE$TRAMPOLINE(<generated>)
	at org.primeframework.mvc.servlet.guice.ServletModule$$FastClassByGuice$$9932012.apply(<generated>)
```

**Comment by robotdan** [comment]
I don't think this is an issue any longer since we are no longer using the Servlet API and Tomcat.
