### ISSUE TITLE
Lots of noise when you use an HTTP method that is not implemented by the action

### ISSUE THREAD

**Issue by robotdan** [prime-framework/prime-mvc#9]
For example, this action does not support `GET`. I think this is just because we aren't adding a result code for `not-allowed`. If we did it would just return `405` I suppose. 

But we could change this to a `DEBUG` message or skip printing the stack trace all together or just when `DEBUG` is enabled. 

```
2022-03-05 4:28:31.330 AM WARN  org.primeframework.mvc.action.DefaultActionMappingWorkflow - The action class [io.fusionauth.app.action.oauth2.TokenAction] does not have a valid execute method for the HTTP method [GET]
2022-03-05 4:28:31.330 AM ERROR org.primeframework.mvc.servlet.PrimeFilter - Error encountered
org.primeframework.mvc.PrimeException: Missing result for action class [class io.fusionauth.app.action.oauth2.TokenAction] URI [/oauth2/token] and result code [not-allowed]
	at org.primeframework.mvc.action.result.AbstractForwardResult.locateDefault(AbstractForwardResult.java:161)
	at org.primeframework.mvc.action.result.AbstractForwardResult.buildFullyQualifiedPath(AbstractForwardResult.java:122)
	at org.primeframework.mvc.action.result.AbstractForwardResult.execute(AbstractForwardResult.java:92)
	at org.primeframework.mvc.action.result.DefaultResultInvocationWorkflow.perform(DefaultResultInvocationWorkflow.java:108)
```

**Comment by robotdan** [comment]
`prime-mvc` will throw a `NotAllowedException` and it is up to the user to bind the `not-allowed` result code, ideally to a `405` status code.
